baseURL = "/"

title = "Fromago"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
enableInlineShortcodes = true
removePathAccents = true

[pagination]
  disableAliases = false
  pagerSize = 20
  path = 'page'

disableKinds = ["taxonomy", "taxonomyTerm"]

