baseURL = "/"
paginate = "10"

title = "Fromago"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
enableInlineShortcodes = true
removePathAccents = true

disableKinds = ["taxonomy", "taxonomyTerm"]

